"""
Offer landing pages — opened from email links generated by the downstream
offer platforms (LangGraph / ADK). Stub implementation for now; the real
look-up will resolve a signed token → customer + offer from Postgres.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, HTTPException, Path, status

from ..schemas import OfferLanding

router = APIRouter(prefix="/api/v1/offers", tags=["offers"])


@router.get(
    "/{token}",
    response_model=OfferLanding,
    summary="Resolve an email-offer token into its landing payload",
)
def get_offer(token: Annotated[str, Path(min_length=10, max_length=128)]) -> OfferLanding:
    if len(token) < 10:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Token too short")

    # TODO: swap for signed-token verification + DB lookup once the
    # customer/offers schema lands. Returning a deterministic stub keeps
    # the contract visible to portal developers.
    return OfferLanding(
        token=token,
        customer_id=UUID("00000000-0000-0000-0000-000000000001"),
        product_sku="WM-EQ-GBL-00001",
        headline="Your personalised ISA offer",
        body=(
            "Based on the information you shared, we think a Stocks & Shares "
            "ISA may be a good fit for your goals. Pick up where you left off."
        ),
        call_to_action="Complete your application",
        expires_at=datetime.now(tz=UTC) + timedelta(days=14),
    )
